server.port: 8088
#spring.devtools.restart.enable: true
spring:
  application:
    name: spring-demo
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10 #心跳等待周期
    lease-renewal-interval-in-seconds: 30 #心跳续约周期
  client:
    register-with-eureka: true #false表示不向注册中心注册自己。
    fetch-registry: true #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    registryFetchIntervalSeconds: 10
    service-url:
      defaultZone: http://localhost:8761/eureka/ #单机版服务注册中心
ribbon:
  ReadTimeout: 6000 #建立连接所用的时间，适用于网络状况正常的情况下，两端两端连接所用的时间
  ConnectionTimeout: 6000 #建立连接后，服务器读取到可用资源的时间
logging:
  level:
    #fei日志
    com.springboot.demo.controller.TestController: debug