server.port: 8088
#spring.devtools.restart.enable: true
spring:
  application:
    name: spring-demo
eureka:
  client:
    register-with-eureka: true #false表示不向注册中心注册自己。
    fetch-registry: true #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    registryFetchIntervalSeconds: 10
    service-url:
      defaultZone: http://localhost:8761/eureka/ #单机版服务注册中心